default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "pguser" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "pguser123" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "ai_invoices_development" } %>

test:
  <<: *default
  database: ai_invoices_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
